#!/bin/sh

cp /usr/share/ldraw/$1 $1
git add -f $1
git commit -a -m "Add $1"

files=$(rg -oP "[^ ]*\\.dat" $1 | sed "s/\\\\/\\//")

for f in $files; do
    echo "Adding $f..."
    cp -f /usr/share/ldraw/p/$f p/$f
    git add -f p/$f
    git commit -a -m "Add $f"

    cp -f /usr/share/ldraw/parts/$f parts/$f
    git add -f parts/$f
    git commit -a -m "Add $f"
done
