#!/bin/sh

files=$(rg -oP --no-filename "[^ ]*\\.dat" parts | sed "s/\\\\/\\//" | sort | uniq)
echo $files

for f in $files; do
    echo "Adding $f..."
    cp -f /usr/share/ldraw/p/$f p/$f
    git add -f p/$f
    git commit -a -m "Add $f"

    cp -f /usr/share/ldraw/parts/$f parts/$f
    git add -f parts/$f
    git commit -a -m "Add $f"
done
